### PR TITLE
Added button to remove invalid values from text area

### PR DESCRIPTION
**Pull request by rennomarcus**
Added feature to remove invalid values from text area in the query/search area.

### CODE REVIEW

**Comment by bruth** [comment]
Thanks @rennomarcus. Could you provide a snippet of what this looks like as screen shot? Also this may be better as a configurable option. This can be done by adding a new field to [the config defaults](https://github.com/chop-dbhi/cilantro/blob/master/src/js/cilantro/config.js), importing it, and then adding a conditional in the code.

**Comment by rennomarcus** [comment]
Hi, @bruth. Thanks for taking a look and explaining how is done. I added the property that can disable the button in the config file as you suggested. Below you can see a screenshot of how it currently looks on the search component 

screen shot 2017-08-04 at 1 32 01 pm

**Comment by bruth** [comment]
Code is looking good. Have you considered putting the button to the left of the "clear" button to align the actions for textarea? Also maybe phrase it "clear invalid values" to be consistent with "clear"? On that note, with this new button it may be more explicit to have "clear all". What are your thoughts?

**Comment by rennomarcus** [comment]
Sounds good to me. With this line of thought, it would probably be a good idea to change the color of the button to red as well. What do you think? 
We also thought about placing the button within the box that shows the list of invalid values, but I thought it'd be more consistent leaving in the search component.

**Comment by bruth** [comment]
Sorry for the delay. Using red would be fine or grey since it is less "destructive" of an action.

**Comment by rennomarcus** [comment]
Thanks, I will change the color and submit again

**Comment by rennomarcus** [comment]
@bruth , I changed the color of the button to grey. Let me know what you think.
screen shot 2017-08-10 at 11 35 18 am

**Pull request merged**
